### ISSUE TITLE
IBC integration

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#114]
## Context
Currently the `magpie` module relies on a custom-made signature in order to create the session that users should use in order to post messages from different chains. As this system is pretty complex and custom, I think that it's better to swap it with the implementation of [IBC, Inter-Blockchain Communication](https://cosmos.network/ibc/) once it is released. 

## Roadmap
- [ ] Allow the Cosmos team to complete the IBC integration. 
- [ ] Study how the can implement the IBC into Desmos to allow cross-chain user registration and post creation
- [ ] Implement IBC into Desmos

### Tracking IBC progress
Currently, to track the IBC progress we can rely on the [Master IBC issue inside Gaia's repo](https://github.com/cosmos/gaia/issues/201).
